version: '2' 
services:
  mysql:
    build:
            context: .
            dockerfile: Dockerfile.sql
    environment:
      MYSQL_DATABASE: billdb
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306" 
  web:
    build:
            context: .
    ports:
     - "5000:5000"
    depends_on:
     - "mysql"
    volumes:
     - .:/code

