version: '2' 
services:
  web:
    build:
            context: .
    ports:
     - "5000:5000"
    volumes:
     - ./in:/in
     - ./out:/out
  mysql:
    build:
            context: .
            dockerfile: Dockerfile.sql
    environment:
      MYSQL_DATABASE: billdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3302" 
