test_name: HEALTH API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: health test

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/health
      method: GET

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0
---
test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/rates
      method: POST
      json:
        file: "rates.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0
---
test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES WRONG PARAMETERS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/rates
      method: POST
      json:
        file1: "rates.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 500
      body:
        errorCode: -5
---
test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES WRONG PARAMETERS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/rates
      method: POST
      json:
        file: "rates2.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 500
      body:
        errorCode: -4
---
test_name: PUT PROVIDER API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: PUT PROVIDER

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/provider
      method: PUT
      json:
        id: 10001
        newname: "newname"        
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0
---
test_name: PUT PROVIDER API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: PUT PROVIDER WRONG PARAMS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/provider
      method: PUT
      json:
        id: "asd"
        newname: "newname"        
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: -3
---
test_name: PUT PROVIDER API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: PUT PROVIDER WRONG KEYS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/provider
      method: PUT
      json:
        id1: "asd"
        newname: "newname"        
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: -5
---
test_name: PUT PROVIDER API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: DB ERROR

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/provider
      method: PUT
      json:
        id: "asd"
        newname: "newname"        
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: -3
---
test_name: GET RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: GET RATES

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/rates
      method: GET
     

    # ...and the expected response code and body
    response:
      status_code: 200
---
test_name: PUT TRUCK API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: PUT TRUCK

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/truck
      method: PUT
      params:
        id: "222-33-111"
        name: "Provider 1"        
      headers:
        content-type: application/text

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0    
---
test_name: PUT TRUCK API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: MISSING PARAMETERS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/truck
      method: PUT
      params:
        name: "Provider 1"        
      headers:
        content-type: application/text

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: -5  
---
test_name: PUT TRUCK API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: MISSING PARAMETERS

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/truck
      method: PUT
      params:
        id: "222-33-111"
        name: "Provider"        
      headers:
        content-type: application/text

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: -5  
---
test_name: GET TRUCK API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: GET TRUCK CHECK

    # Define the request to be made...
    request:
      url: http://0.0.0.0:5000/truck/c-11111
      method: GET
      params:
        from: "09950326000000"
        to: "30000000000000"        
      

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0  



