version: '2' 
services:
  web:
    build:
            context: .
    ports:
     - "8089:5000"
    volumes:
     - .:/code
  mysql:
    build:
            context: .
            dockerfile: Dockerfile.sql
    environment:
      MYSQL_DATABASE: billdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "8087:3302" 