version: '2' 
services:
  web:
    build:
            context: ./flask
            dockerfile: ./flask/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - .:/code
  mysql:
    build:
            context: ./mysql-db
            dockerfile: ./mysql-db/Dockerfile
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 0.0.0.0
      MYSQL_USER: testing
      MYSQL_PASSWORD: testing
    ports:
      - "3306:3306" 
