test_name: GET RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: GET RATES

    # Define the request to be made...
    request:
      url: http://green.develeap.com:8090/rates
      method: GET
     

    # ...and the expected response code and body
    response:
      status_code: 200

