test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES

    # Define the request to be made...
    request:
      url: http://green.develeap.com:8090/rates
      method: POST
      json:
        file: "rates.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 200
      body:
        errorCode: 0
---
test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES WRONG PARAMETERS

    # Define the request to be made...
    request:
      url: http://green.develeap.com:8090/rates
      method: POST
      json:
        file1: "rates.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 500
      body:
        errorCode: -5
---
test_name: POST RATES API

# ...and each test has one or more stages (e.g. an HTTP request)
stages:
  - name: POST RATES WRONG PARAMETERS

    # Define the request to be made...
    request:
      url: http://green.develeap.com:8090/rates
      method: POST
      json:
        file: "rates2.xlsx"
      headers:
        content-type: application/json

    # ...and the expected response code and body
    response:
      status_code: 500
      body:
        errorCode: -4


